### ISSUE TITLE
login API endpoint changed

### ISSUE THREAD

**Issue by ohmantics** [pallavkothari/hover#57]
Looks like it's https://www.hover.com/api/login now. With that change, I can at least list domains; haven't tried out other APIs yet as my domains are still Pending Transfer.

**Comment by pallavkothari** [comment]
Thanks for reporting - I pushed a fix for the login URI, but unfortunately I don't have any domains on hover anymore, so it's hard for me to verify other fixes. Anyway, hope this helps you out.
